### ISSUE TITLE
Codes for Evaluation

### ISSUE THREAD

**Issue by Chan-1996** [osehmathias/lisa#1]

**Comment by Chan-1996** [comment]
Hi, I am very interested in your nice work. Could you provide the codes for evaluation? I find it is difficult to reproduce your results, especially for AGIEVAL and WINOGRANDE.

**Comment by osehmathias** [comment]
hey 👋 
this was made with LMFlow, you might find some evaluation scripts useful there 
https://github.com/OptimalScale/LMFlow/tree/main/scripts
